### ISSUE TITLE
Localization: Brazilian Portuguese, is listed twice and Portuguese Portugal is not listed

### ISSUE THREAD

**Issue by mike-pt** [pcbsd/lumina#166]
I'm assuming one of the Brazilian Portuguese is just missnamed.

I'm not sure how this is done, but I did notice this:

file: lumina-fileinfo/i18n/lumina-fileinfo_pt.ts b/lumina-fileinfo/i18n/lumina-fileinfo_pt.ts

----> <TS version="2.1" language="pt_BR">
shoun't it be ==> <TS version="2.1" language="pt_PT">

same for file --> lumina-xconfig/i18n/lumina-xconfig_pt.ts b/lumina-xconfig/i18n/lumina-xconfig_pt.ts

thanks

**Comment by beanpole135** [comment]
Are you talking about this line in the `*_pt[_BR].ts` files?
`<TS version="2.1" language="pt_BR">`
I just fixed that tag in the `lumina-fileinfo_pt.ts` file for you: https://github.com/pcbsd/lumina/commit/2380983a8d4ad03bb3c63f16913e62ffce8e0ddc

The project file appears correct (pt and pt_BR listed), and the translation files are auto-generated/updated by the Qt "lrelease" utility before getting committed to the source tree and plugged into the Pootle translation systems, so I am not sure exactly what caused the mismatched tag to get inserted into the file - let me know if you see any other like that which are also mismatched and we can manually adjust/fix those.

**Comment by mike-pt** [comment]
hum.. the issue is still there, I.E when I go to the lumina menu (new start menu like) and click quick setings the list of locales shows 2 Portuguese Brasil and none Portugue Portugal.

Also picking any doesn\t seem to make any change at all, It goes back to American English

**Comment by beanpole135** [comment]
Ok, I just spent a bit of time looking into this and found two bugs:
1) The Locale selector(s) were not properly reflecting the current locale settings after you make a change. This was just fixed in source a moment ago (QLocale was not reading the right settings - I bypassed it to read the environment directly).

2) Both "pt" and "pt_BR" locales are showing up in the selector as "Portuguese Brasil". This is directly caused by something in Qt itself is returning the wrong localized name: `QLocale locale("pt"); locale.nativeLanguageName();`
I might be able to bypass this for now - but the ultimate solution is to get it fixed in Qt itself.

**Comment by beanpole135** [comment]
Ok, I just put a small bypass for this Qt bug into Lumina, so that you should now see the native language name of "pt_PT" for the "pt" locale instead (looks like a translation of "European Portuguese" to my english-only eyes).

https://github.com/pcbsd/lumina/commit/f2afb1e0689a5a5077e28c3c65dc71df19cf7fbe
