### ISSUE TITLE
No save buttons in Desktop configuration when changing the auto-started applications

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#86]
I don't know why, but the "button "save changes" is not available when you click on the "Applications" top button.

To save the changes, users must go to an another panel and click "save changes". 

If I'm not wrong, I see that you do it deliberaly: "  //Hide the save button for particular pages". 
But I don't understand the reason.

**Comment by beanpole135** [comment]
Ah, that page has all the changes occur instantly, so the "save" button does not apply to anything on that page. I should probably make that button visible if there are changes from *other* pages still waiting to be saved though... :-)

**Comment by beanpole135** [comment]
Fixed!
If the save button is active when you change to that page, it should now stay visible until the current changes are saved to their respective files.

**Comment by william-os4y** [comment]
There is no save button by default. 
I add an application in the auto-start list, but the save button does not appear. 

Issue remains: 
when we add or delete an application from the auto-start, we must switch to an another tab to save the change. 

I don't understand why on this tab there is no "save changes" since we can perform changes.

**Comment by beanpole135** [comment]
Ah, I think I see what you are saying now.
The "default applications" tab does not need the save button since changes there are instantly performed on the system, but with the recent redesign of where some pages/tabs are now located, the "Autostarted Items" tab is also on that page but *does* need the save button.

I just removed that save button disabling line, so that should now work for you without problem.

**Comment by william-os4y** [comment]
It works. 

Except that now the button desapear, instead of been grey.
